### ISSUE TITLE
ImportError: cannot import name '_meters_per_pixel' from 'rio_cogeo.utils' 

### ISSUE THREAD

**Issue by RichardScottOZ** [developmentseed/cogeo-mosaic#155]
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-4dca56063927> in <module>
     18 from rasterio.windows import Window
     19 
---> 20 from rio_cogeo.utils import _meters_per_pixel
     21 from rio_cogeo.cogeo import cog_translate
     22 from rio_cogeo.profiles import cog_profiles

ImportError: cannot import name '_meters_per_pixel' from 'rio_cogeo.utils' (C:\Users\rscott\AppData\Local\Continuum\anaconda3\envs\pangeo\lib\site-packages\rio_cogeo\utils.py)

Is this version from an old github install perhaps?

I am looking at the notebook you suggested on twitter  https://github.com/developmentseed/awspds-mosaic/blob/master/notebooks/LargeScaleMosaic.ipynb

**Comment by vincentsarago** [comment]
The notebook is pretty old, we have done many improvement since.

if you give me couple days I might be able to update the notebook and host in on https://github.com/developmentseed/titiler-pds/tree/master/demo (ref: https://github.com/developmentseed/titiler-pds/issues/3)

I'll closes this issue because it's not linked with cogeo-mosaic directly

**Comment by RichardScottOZ** [comment]
Sure, thanks Vincent, that would be great  - I just saw https://github.com/cogeotiff/rio-cogeo too.
