### ISSUE TITLE
Support retrieving entire MosaicJSON entity with DynamoDB and SQLite backends

### ISSUE THREAD

**Issue by philvarner** [developmentseed/cogeo-mosaic#175]
As a user, I would like support for retrieving the entire MosaicJSON entity in a backend-agnostic way. Currently, read has different behavior for different backends, I assume to improve performance for these backends. This has the effect that read operations from these backends result in different entities, which is confusing to clients. 

Currently, both the DynamoDB and SQLite backends erase the `tiles` property from the MosaicJSON when it is read from the datastore. 

In `_read`:

```
meta["tiles"] = {}
```

the `mosaic_def` field value then has an empty `tiles` field.  

This has the effect of preventing a caller from accessing the entire MosaicJSON. DynamoDB is restricted even further, in that only a single quadkey can be retrieved.

Possibly, there should be another function that will return the entire MosaicJSON entity.

**Comment by vincentsarago** [comment]
👍 @philvarner The problem is that for DynamoDB it will be quite costly to retrieve each tiles! I understand this is not really user friendly. The way the backend classe is designed I'm not sure what's the best way to do this. 

for now a users could do 
```python
with DynamoDBBackend(...) as mosaic:
    m = mosaic.mosaic_def()
    tiles = [mosaic._fetch_dynamodb(qk) for qk in mosaic._quadkeys]
    mosaic_def = MosaicJSON(**m.to_dict(exclude_None=True).update({"tiles": tiles}))
```

**Comment by philvarner** [comment]
Thanks for that suggestion!

**Comment by kylebarron** [comment]
The original point of adding the DynamoDB backend was to have a serverless, hosted database with very fast reads for single keys at a time. In order to reconstruct an entire mosaic from DynamoDB, you'd have to read every quadkey individually, as vincent says, or somehow download the entire table using boto3 directly. In any case, it would be very slow and (relatively) quite expensive.

IMO if you require support for retrieving the entire MosaicJSON, you should just prevent usage of the DynamoDB backend (I'm not as familiar with the sqlite backend).

**Comment by philvarner** [comment]
I'm fine with just having this documented, maybe with an Optional type annotation that it doesn't work for all backends. Also putting the code Vincent provided above with how to do this if you really want to.
